#ifndef LUMIRAIL_DIGIKEY_ESP32S3_CONFIG_H
#define LUMIRAIL_DIGIKEY_ESP32S3_CONFIG_H

#define UART_MODULE_BAUD 115200
#define UART_RX_PIN 39
#define UART_TX_PIN 38
#define LINE_BUF_MAX 256
#define SCENE_BINARY_IDLE_MS 400

#define SCENE_SIZE_PFX_LEN 11
#define SCENE_HASH_PFX_LEN 11
#define SCENE_HASH_HEX_LEN 64
#define MODULE_SEND_PFX_LEN 11

#endif
