#ifndef LMS_L1_ESP8266_CONFIG_H
#define LMS_L1_ESP8266_CONFIG_H

#define SERIAL_BAUD 115200

#define BOARD_FILE "/board.txt"
#define CONFIG_FILE "/config.txt"

#define SCENE_TMP "/scene.tmp"
#define SCENE_BIN "/scene.bin"
#define SCENE_BAK "/scene.bak"

#define PAGE_SIZE 512

#define LINE_BUF_MAX 96
#define SCENE_LINE_BUF_MAX 256
#define SCENE_STATE1_IDLE_MS 2000
#define LINE_ACK_TIMEOUT_MS 1000
#define STANDALONE_PING_TIMEOUT_MS 3000
#define STANDALONE_GRACE_AFTER_UPLOAD_MS 15000

#define SCENE_HASH_PFX_LEN 11
#define SCENE_HASH_HEX_LEN 64
#define SCENE_DUMP_CMD_LEN 10
#define SCENE_DUMP_CHUNK 16
#define GET_SCENE_HASH_PFX "GET_SCENE_HASH:"
#define GET_SCENE_HASH_PFX_LEN 15
#define SCENE_UPLOAD_START_PFX "SCENE_UPLOAD_START:"
#define SCENE_UPLOAD_START_PFX_LEN 18
#define SCENE_START_PFX "SCENE_START:"
#define SCENE_START_PFX_LEN 12
#define SCENE_BLOCK_PFX "SCENE_BLOCK:"
#define SCENE_BLOCK_PFX_LEN 12
#define SCENE_BLOCK_SIZE 256
#define DEBUG_SCENE 1
#define GETFILE_HEX_LINE 32

#define SETCONFIG_PFX "SETCONFIG:"
#define SETCONFIG_PFX_LEN 10
#define SET_SCENE_META_PFX "SET_SCENE_META:"
#define SET_SCENE_META_PFX_LEN 15

#define DEBUG_RX 0

#define LFP_MAX_DIR_LEN 512
#define LFP_MAX_CHANNELS 64
#define LFP_MAGIC 0x3150464C
#define LFP_DIR_MAGIC 0x31524944
#define LFP_CHUNK_FRAM 0x4D415246

#endif
