#ifndef LMS_L1_ESP32S3_CONFIG_H
#define LMS_L1_ESP32S3_CONFIG_H

#ifndef LMS_L1_SD_TEST_MODE
#define LMS_L1_SD_TEST_MODE 1
#endif

#ifndef LMS_L1_USE_NATIVE_USB
#define LMS_L1_USE_NATIVE_USB 0
#endif

#ifndef PC_UART_RX
#define PC_UART_RX 44
#endif
#ifndef PC_UART_TX
#define PC_UART_TX 43
#endif

#define USE_SPIFFS 1

#define UART_MODULE_BAUD 115200
#define UART_RX_PIN 39
#define UART_TX_PIN 38

#define LED_RUN_PIN 1
#define LED_MODULE_PIN 2
#define LED_AUX_PIN 39
#if (LED_AUX_PIN == UART_RX_PIN)
#define LED_AUX_USABLE 0
#else
#define LED_AUX_USABLE 1
#endif
#define STATUS_LED_FLASH_MS 75
#define MODULE_LED_PONG_HOLD_MS 20000
#define LINE_BUF_MAX 256
#define MODULE_TO_USB_BUF_SIZE 2048
#define MODULE_TX_BUF_SIZE 512
#define SEND_TO_MODULE_START_OK_MS 5000
#define SEND_TO_MODULE_BLOCK_OK_MS 10000
#define SEND_TO_MODULE_FINAL_OK_MS 15000
#define MODULE_KEEPALIVE_PING_MS 1000
#define SCENE_START_PFX "SCENE_START:"
#define SCENE_START_PFX_LEN 12
#define SCENE_HASH_PFX_LEN 11
#define SCENE_HASH_HEX_LEN 64
#define SCENE_BRIDGE_BLOCK_SIZE 256
#define SCENE_BRIDGE_TMP "/scene.tmp"
#define SCENE_UPLOAD_START_PFX "SCENE_UPLOAD_START:"
#define SCENE_UPLOAD_START_PFX_LEN 18
#define SCENE_SEND_TO_MODULE_PFX "SCENE_SEND_TO_MODULE:"
#define SCENE_SEND_TO_MODULE_PFX_LEN 20
#define SCENE_BLOCK_PFX "SCENE_BLOCK:"
#define SCENE_BLOCK_PFX_LEN 12
#define SCENE_BRIDGE_SEND_CHUNK 32
#define SCENE_BRIDGE_MAX_RECV_MS 15000
#define MODULE_SEND_PFX_LEN 11
#define DEBUG_SCENE 1

#define USB_PRODUCT_NAME   "Lumirail LMS-L1 ESP32-S3"
#define USB_CDC_IFACE_NAME "Lumirail LMS-L1 ESP32-S3"
#define USB_MANUFACTURER   "Lumirail"
#define USB_SERIAL_NUMBER  "1"

#define LMS_L1_BOOT_MSG "LM-L1-S3 115200\n"

#ifndef SD_SWAP_MISO_MOSI
#define SD_SWAP_MISO_MOSI 0
#endif

#ifndef SD_RAW_PROBE
#define SD_RAW_PROBE 0
#endif

#ifndef DBG_UART_RX
#define DBG_UART_RX PC_UART_RX
#endif
#ifndef DBG_UART_TX
#define DBG_UART_TX PC_UART_TX
#endif

#include "sd_pins.h"

#endif
