export { serialConnection, estimateUploadTimeMs, LFP_BLOCK_SIZE } from './serialConnection'
export type { ModuleInfo, UploadSceneOptions, UploadLfpOptions } from './serialConnection'
export { isValidModuleSerial } from './moduleSerial'
export type { SerialConnectionState, SerialPort } from './types'
export type { PortLike } from './serialConnection'
